### ISSUE TITLE
Text encoding issues while switching between different messages

### ISSUE THREAD

**Issue by mobileartur** [mikehardy/thunderlink#14]
The previous version and the new beta sometimes show messages with incorrect text encoding. I usually have messages with Unicode, Western, Central European (Windows) and Central European (ISO). Sometimes after clicking a thunderlink:// messages are shown with Unicode or Western, but the should be in CE (Windows) or CE (ISO). When I click directly the same messages in Thunderbird they are always OK.

I will try to check how to reproduce this bug and will post steps here.

**Comment by mikehardy** [comment]
In the general style of "steps to reproduce" / "what you expected" / "what happened",

It sounds like:

1- mail message in (for example) Western, thunderbird set to Central European (Windows)
2- click Western encoded mail message in thunderbird message list, displays in Central European (Windows)
3- click thunderlink outside thunderbird for the western-encoded mail message

Expected: thunderbird displays it in Central European
Actual: thunderbird displays it in western

Is that right?
