### ISSUE TITLE
Enhancement: help windows users with .reg files ready to install

### ISSUE THREAD

**Issue by mikehardy** [mikehardy/thunderlink#16]
Based on the discussion in #7  (and #13 ) it seems like it would be a big help to windows users if we had some .reg files in the repository to help them out. I could link to them in release page on our add-ons registry listing, and windows people could just install thunderlink, then download the reg file and be done

If anyone could propose a pull request with a registry file they know worked, labeled for the versions of windows they know worked, I'd be happy to include it.

@olifair or @mobileartur either of you want to give it a shot? Or just attach the one you used to this issue here if you're not familiar with github yet?

Thanks!

**Comment by mobileartur** [comment]
I created new .reg files and a pull request.

**Comment by mikehardy** [comment]
Thank you! I went even further with the readme and just deleted most of the Windows section, replacing it with links to these files - now for Windows users I think it's super easy, should be a much better experience for any new users

**Comment by mobileartur** [comment]
Great! However Windows 8 version is still unknown. I don't have any PC with Win 8 at the moment.

**Comment by mikehardy** [comment]
The beauty of open source :-), we do the best we can and then let it go. If anyone has win8 and wants it to work, with the files you made available they should be able to get going

**Comment by nomatica** [comment]
I wanted to say thank you. This made using this add on possible for me.
