### ISSUE TITLE
Right-click context menu shows even when there is no message selected

### ISSUE THREAD

**Issue by mikehardy** [mikehardy/thunderlink#21]
If you have a message selected, the right click menu to make a thunderlink should show, but if you have no messages selected or you have multiple messages selected it should not show

**Comment by mobileartur** [comment]
I was trying to recreate this, but I always have one selected message, so there is always the Thunderlink sub-menu. 

If I select multiple messages I also have the Thunderlink sub-menu to create multiple links at once. 

Hmmm?

**Comment by mikehardy** [comment]
It is when you first open TB, so not a super seriously issue but it does happen...

**Comment by mobileartur** [comment]
When I open TB I have no messages selected and the right view pane is blank. I can't open any right click menu there. When I right click on any message from the list, I can create a thunder link and that's OK.

**Comment by mobileartur** [comment]
> 
> 
> It is when you first open TB, so not a super seriously issue but it does happen...

Or maybe first time after installation? I close and reopen TB to reproduce this issue, but everything seems OK.
