### ISSUE TITLE
Preferences dialog incorrect on Windows and with some themes (e.g. DeepDark)

### ISSUE THREAD

**Issue by mikehardy** [mikehardy/thunderlink#23]
If you use a non-default theme, the preferences dialog appearance is incorrect, with some of the checkboxes not even showing up correctly (they appear checked even though their programmatic state is unchecked).

It is still possible to configure things and the preferences are saved correctly but it is not a great experience.

Using the built-in themes works perfectly.

**Comment by UkkariVoronoi** [comment]
Thunderbird 60.4.0 with Thunderlink v-1.2.6-tb.xpi is not able to show Thunderlink options correctly.
When choosing "By selecting mailbox", the background color of sub-window is completely transparent. Then it is difficult to read and choose the option. In addition, Thunderbird freezes just after the choice of "By selecting mailbox". But "By selecting mailbox" function works well after the restart of Thunderbird. Thunderlink v-1.2.6-tb.xpi seems to have some troubles to adapt to the new "add-on option" menu in Thunderbird 60.x.

**Comment by mikehardy** [comment]
Hmm - thanks for the report @UkkariVoronoi  - are you using any themes or this with stock 60.4 ? Because with stock 60.2 it worked well, or at least it seemed to.

**Comment by UkkariVoronoi** [comment]
Thank you for your reply. I am not using any themes. I have never checked Thunderlink v-1.2.6-tb.xpi with Thunderbird 60.2.x.

**Comment by mikehardy** [comment]
Hmm - I'm not able to reproduce this on TB 60.4.0 on macOS 10.14.2. I was using a fresh install of Thunderbird, with the only configuration being to connect it to one gmail account prior to downloading the Thunderlink add-on, restarting thunderbird to enable it, then checking the preferences dialog.

I did notice that the setting to open in mailbox was saved (it's called "bySelecting" in the advanced preferences editor) but the preferences dialog does not correctly position the dialog box to it when re-opening preferences each time, so that's a problem.

But I saw no problem with transparency or with freezing. 🤔 

@UkkariVoronoi  Is there a way you could try a new user on your machine - or similar - so you could try this with a fresh + empty thunderbird install? Until I can reproduce something I can't fix it unfortunately. Cheers

**Comment by UkkariVoronoi** [comment]
I have checked Thunderlink v-1.2.6-tb.xpi/v-1.2.3-tb.xpi on TB 60.4.0 on Windows 7 Professional (64bit).
The same problem I have mentioned occurs. Once I have selected "By selecting mailbox", which causes freezing of TB, I can use Thunderlink without any troubles after the selection.
I am going to check the problem with a fresh TB install.

**Comment by mikehardy** [comment]
@UkkariVoronoi - I have a suspicion this may have to do with localization and font etc - can you tell me what language you have the system set to, and what language you have thunderbird set to? I do have access to a Win10 machine, maybe I can reproduce it?

**Comment by UkkariVoronoi** [comment]
Thank you for your reply. I use the Japanese locale version of Windows 7 professional (64bit).
My current user interface of Thunderbird is Japanese. The default font of Thunderbird is ”Meiryo", which is a Japanese sans-serif gothic typeface.

**Comment by kgorlen** [comment]
Same issue as @UkkariVoronoi w/ Thunderbird 60.4.0 and thunderlink 1.2.7, Win10, en-US.

**Comment by mikehardy** [comment]
@kgorlen - with win10 and en-us! that is unexpected. but also my set of versions, except the part where I don't use it normally on windows (sorry!). I do have a win10 virtual machine though, so this may be easy for me to reproduce. Thanks for the report

**Comment by kgorlen** [comment]
The last update to thunderlink broke all cntrl-alt shortcuts and all the 
"Copy ..." menu items except "Copy thunderlink to clipboard".  I've been 
too busy moving to report the new problems.  Is there a version to which 
I can roll back?

Thanks.

**Comment by mikehardy** [comment]
Oh no! I am really sorry to hear that. I think they are all working for me so I am not sure what is going on but I will of course look.

On the thunderbirds add-on site you can find all the old versions, plus I have all the releases I have generated on the releases page here too - just make sure to turn *off* auto-update on the plugin after installing it from a file or it may try to take you back to 1.2.7?

https://github.com/mikehardy/thunderlink/releases

**Comment by mikehardy** [comment]
Okay, I can replicate that on windows the Ctrl-Alt-N shortcuts do not seem to work, and I also see the horribly broken preferences problem. I was able to get other right-click thunderlinks to work copy correctly into the clipboard on thunderlink 1.2.7 / win10 / Thunderbird 64 though, so I cannot replicate that. Maybe there is a problem with your preferences? (which would be possible to fix in the advanced editor maybe, since the main preference pane looks so terrible on windows right now - sorry)

**Comment by mikehardy** [comment]
I was able to investigate this today, but I don't have a solution yet.

1. this only affects Windows. Linux and Mac preferences work okay (except for dark theme support). Unfortunately Windows is the majority of thunderlink users.
1. this is related to dynamic preference UI construction. What happens is that the preferences UI is partially defined in XUL directly, and partially built dynamically via Javascript action on the DOM. I don't know why, but it looks to me like on Windows the static XUL part is being visually overwritten by the dynamic DOM part

That makes me think the solution will be to move either entirely to DOM manipulation, or entirely to XUL for it to work well.

Since XUL is on the way out, I would guess moving entirely to DOM would be best.

I don't have the time today to do that, but that would be my preferred patch - something that takes [the remaining XUL parts](https://github.com/mikehardy/thunderlink/blob/master/chrome/thunderlink/content/preferences.xul#L90) and puts them all in the Javascript/DOM part that generates the tab panel around here: https://github.com/mikehardy/thunderlink/blob/master/chrome/thunderlink/content/preferences.js#L16

**Comment by mikehardy** [comment]
I think I just fixed this, it'll be released in 1.2.9
