### ISSUE TITLE
Email opening as blank

### ISSUE THREAD

**Issue by dmusican** [mikehardy/thunderlink#25]
I'm having an intermittent problem with thunderlink where the link fires up the email in Thunderbird, but the email opens as completely blank. By blank, I mean that the window is entirely white, including the headers (i.e., they're missing). I do know that it found the right email, because I can see the subject in the title bar of the window itself. I do see the menu bar and the toolbar below it, but below that... nothing. This problem happens for _some_ emails, and I can't say why it works for some emails and some others. But for the emails where it goes wrong, it keeps happening reliably with the same email, at least for a while. I was going to report this a few days ago, but then for a particular email for which I was having trouble, it started working properly again. But right now, I've got a particular email for which it's reliable happening, and I can't guess as to why.

I've tried looking in the Thunderbird debug window, but there's nothing there. I'm running Thunderbird 60.2.1, Ubuntu 18.04.1, Thunderlink 1.2.6. Any thoughts?

**Comment by dmusican** [comment]
Thanks, @mikehardy. I did just rebuilt the index on the folder where the target email was (right click, Properties, Repair Folder), and it solved the problem for the email I had it on hand. So that's good news. I don't have any other emails at the immediate moment for which it's going wrong, so we'll see.

Interestingly, in this last case, it was not only showing a blank email, but it was /also/ showing the wrong title in the window title bar, i.e. it was simultaneously experiencing #12. Again, in this single case, the folder repair fixed it. Thanks for the advice! I'll see what happens going forward.

**Comment by mikehardy** [comment]
Glad to see that worked! Fingers crossed it continues to work well. I'm going to close this now but if it recurs and we can pin something down we'll obviously reopen. Cheers
