### ISSUE TITLE
Appending Thunderlink to file

### ISSUE THREAD

**Issue by MarioKusek** [mikehardy/thunderlink#28]
I am using Taskpaper for my tasks. It is text based task list. For integration with thunderlink it would be nice to have possibility to append link to file instead of copying it to clipboard. 

In preferences can be added 2 parameters in each tab:
- checkbox - Append to file
- text field - Path to file

If checkbox is ticked than it will append to file, otherwise not. 

Regarding copying to clipboard there are two possibilities:
- it could do always copy to clipboard or
- if it is appended to file clipboard will not be changed. In this case this need to be documented or emphasized in checkbox.

What do you think about that?

If you agree I can make implementation and create PR for that.

**Comment by mikehardy** [comment]
Seems fine by me as long as the code is clean - I highly recommend eslint as I already have a project config for that. As long as the UI makes it obvious what's happening with whatever choice is fine by me. Simpler is usually best - just checkboxes maybe?
