### ISSUE TITLE
Feature Request: Open email in tab / in context

### ISSUE THREAD

**Issue by ivanperez-keera** [mikehardy/thunderlink#40]
Hi,

I love this plugin, but one of the issues I have is that emails are opened in a separate window, so it's hard to know where the email is located (in which folder) in one's mailbox. Knowing the folder is important to have additional context and find related emails (including the conversation it belongs to).

Thunderbird has two options to find an email's context: 'Open in Conversation' and 'Open Message in Containing Folder'. Unfortunately, none of them work if the email is opened in a separate window, only if the email is opened in a tab.

I could not find any command line option for thunderbird to tell it to use a tab (the generic `-new-tab` option presumably needs an argument and is for the browser). Perhaps there is one, or maybe we want to open a feature request on thunderbird's page?

**Comment by mikehardy** [comment]
Hi there! Glad you like the add-on. I think what you're looking for is actually implemented and available in the preferences in a drop box for how to open the message. By default we open into a new window because it's the most reliable by you can do a tab or in the message pane if I remember correctly? If I remember correctly there may also be an issue related to opening by selecting the message - #11 - but please give it a try and let us know

**Comment by ivanperez-keera** [comment]
Thanks for the quick response.

I think what happened is that I expected addon preferences to be where addons are (which I believe they used to be and, at least in Firefox, they still are), but Addon Preferences have their own menu under Tools.

Issue #11 affects me too, but I think it's unrelated (my issue was just I couldn't find a way to open in a new tab). I have found it now. This works for me and fixes my issue.

Thanks!

**Comment by mikehardy** [comment]
Yeah, thunderbird add-ons is kind of wild and wooly from an API and developer-support perspective. It's kind of a wonder I/we (as add-on developers) are able to make anything work :-). But we try ;-). Glad you found the pref you needed, and if you have anything to add to #11 with regards to exact scenarios to reproduce or anything, that could help. Cheers
