### ISSUE TITLE
How do you use Thunderlink?

### ISSUE THREAD

**Issue by nomatica** [mikehardy/thunderlink#42]
Not an issue, and inquiry. I am interested in knowing what other programs/applications people are using thunderlink with? The potential of linking directly to emails is extremely powerful. Originally I installed the addon with the hopes that I could use it within Thunderbird's tasks and events management; that it would allow me to create an event or a task and easily link to the email with pertinent information. If this didn't work I might be able to use thunderlink in conjunction with an Excel/libre calc document. However I'm sure there are other options. How are you using thunder link as a part of your workflow?

It occurs to me that the “amend file” option could also be extremely powerful. I'm curious if anybody is using this function and if so what file type are the amending? I assume it might be possible to have thunder link automatically input into a specific column in a lever office spreadsheet. However I'm not positive how to go about that and maybe there is another option that is far more user-friendly.

**Comment by mikehardy** [comment]
amend file is from @MarioKusek - he may have ideas there

as mentioned separately I use toodledo (paid subscription unfortunately) or google keep (cloud service, but available free). Basically any todo or sticky note system should work, like a wiki even. I strongly prefer solutions that synch across mobile and desktop but are available offline, but I don't like hosting my own systems if I can avoid it, thus my choices - and obviously everyone has different preferences

I'm also curious what people use, good question.

**Comment by nomatica** [comment]
Totally understand. With further experimentation this will also work with reminder Fox. It is somewhat quicker to create a task with reminder Fox then with Thunderbird and lightning.

I agree that what makes funder link so powerful is its ability to be used with virtually anything you can copy and paste to.

I am curious to learn more about how the amend file option works. Will this work with a Comma delineated text? Or spreadsheet?. Or does it just work with basic text files. What would be great is for the links to incrementally be added to a document creating a list

**Comment by mikehardy** [comment]
You should try the file writing, you get to configure your delimiter, and it appends to file - you'll see it in the preferences

**Comment by nomatica** [comment]
I able to get a thunderlink to feed into a text file, however when I looked at setting up the deliminator, it looks like it works only when choosing multiple emails at a time.  What I thought amend file did was add to a file as you use it.    When I do that,  the links are not separated. The delimiter is only applied when selecting multiple emails?

**Comment by mikehardy** [comment]
Huh - I dunno, have not actually use it - I think @MarioKusek is european time so maybe he'll see this later on today as the sun comes up over there

**Comment by MarioKusek** [comment]
@nomatica Can you give me an example what you want to do?

**Comment by Olifair** [comment]
I'm using FreePlane, a mindmapping software to organize my tasks (and structure them into critical now, target now, this week, follow ups, different long term projects, profiting from the hierarchical structure of a mind map) . And in FreePlane every node (task) can have a link. When setting the link, the content of the clipboard is pasted automatically, so very few clicks. And once set, I get a clickable icon, which will  open directly the email. And similarly to other software, additionally to the text, you have a note field (HTML formattable), dates, reminders and much more.  Check it out here : https://www.freeplane.org/wiki/index.php/Home

**Comment by MarioKusek** [comment]
OK, so what is the problem with thunderlink?

**Comment by MarioKusek** [comment]
The only thing that I don't understand is this question:

> It occurs to me that the “amend file” option could also be extremely powerful. 

Can you please explain what you mean by amend. 

Should it be append?

**Comment by nomatica** [comment]
MarioKusek,
I apologize for the confusion.  It is my fault.  You are correct. It is **append** not **amend**.  I misread it.  For others who might be confused, when you open up thunderlink's options (copied picture), there is a setting where you can "append thunderlink to file"  
I am trying to figure out how to use this setting.  I am curious how others are using it?
If it automatically fed into a task manager or file on my computer that would be an extremely fast workflow. 

I am trying to figure out if it is possible to have this automatically, consecutively, feed into a spreadsheet.    So far I have only been able to get it to feed into a .txt  file, and the links are not separated by anything.  There is the ability to use a multi-select delimiter, but that is when selecting multiple emails.. 

![thunderlink options bottom](https://user-images.githubusercontent.com/49659723/56745650-c14f0b80-6748-11e9-8b5a-63394af1b935.JPG)

**Comment by nomatica** [comment]
@Olifair 
Thanks. I am familiar with Freeplane, though I have not used it.  It has the added benefit of having a portable app as well.  I will take a look at it. 

@MarioKusek I had not hear of Taskpaper.  But Form a quick glance it looks  like a nice interface.

**Comment by MarioKusek** [comment]
@nomatica 
This is my configuration for taspaper:
![image](https://user-images.githubusercontent.com/10060710/56754197-b6b66580-678c-11e9-95d4-b0934363462a.png)

Taskpaper format is textual format and just appending task at the end of file is fine.
You can see that my pattern is:
`\t- <subject>\u2028\tFrom: <sender> on <time>\u2028\t<thunderlink>\n`

First I put tab (`\t`) and then minus sign, space and then subject of email. The `\u2028` is UTF-8 character for line separator. After the I put tab and thunderlink and it finishes with new line `\n`. That way in taskpaper format I create new task at the end of file.

You asked about putting something in spreadsheet. That is not possible because spreadsheets have their format e.g. MS Excel has its format and OpenOffice has its own. That means that thunderlink will need to recognise format and write in that format which mend including libraries for reading such formats and program it. My proposal would be to use [CSV format](https://en.wikipedia.org/wiki/Comma-separated_values). That format can be loaded in Excel and in OpenOffice. But for that Thunderlink would need to implement escaping sequence to generate proper values. If people are interested in that feature in reasonable time we could implement it.

**Comment by mikehardy** [comment]
Ah, that's clever on the append - you've left it basically as a "raw append" in the file, then the user can (and must...) do their own formatting, *including the newline*. So I think that's the key for @nomatica 

Love the references to other software. If someone wants to just copy-paste that into a wiki page here for "Systems Thunderlink Users Use" that would be more than fine by me. Great ideas.

**Comment by nomatica** [comment]
@MarioKusek 
Thank you. Having your example with taskpaper is very helpful. Helped me see few keypoints I was missing.  I quickly experimented with the string settings similar to yours to append a a txt, rtf, and cvs file.  The text file worked the best, however it was a single line, with spacing spacing between each link.  I also tried using the deliminator for cvs, and thought ti was going to work.  I think I need to have the type of text outlines.   I need to experiment more.

Currently I use spreadsheets as part of my workflow, but I do not feel it is a good system.  Previously I relied on a number of thunderbird addons that were very helpful. They stopped working over the years as thunderbird's development has broken many legacy plugins. 

> Taskpaper format is textual format and just appending task at the end of file is fine.
> You can see that my pattern is:
> `\t- <subject>\u2028\tFrom: <sender> on <time>\u2028\t<thunderlink>\n`
> 
> First I put tab (`\t`) and then minus sign, space and then subject of email. The `\u2028` is UTF-8 character for line separator. After the I put tab and thunderlink and it finishes with new line `\n`. That way in taskpaper format I create new task at the end of file.
> 
 I am curious if the reason that my experimenting is not being as fruitful is because i need to specify the text format UTF-8 or otherwise for CVS.   Taskpaper looks very interesting.  I am currently using windows. I think what might be helpful is taking a look at some textual/markdown managers for the windows operating system similar to taskpaper.  

> You asked about putting something in spreadsheet. That is not possible because spreadsheets have their format e.g. MS Excel has its format and OpenOffice has its own. That means that thunderlink will need to recognise format and write in that format which mend including libraries for reading such formats and program it. 

I assumed as much.  However, I did not know if it was possible. 

My proposal would be to use [CSV format](https://en.wikipedia.org/wiki/Comma-separated_values). 
That format can be loaded in Excel and in OpenOffice. But for that Thunderlink would need to implement escaping sequence to generate proper values. If people are interested in that feature in reasonable time we could implement it.
Do you think an escape sequence is needed just to get it into CVS format?   I am not sure if my needs right now, justify needing to develop this feature. In the end, I am looking for a solution where I can keep track of emails as they relate to different tasks and projects I am involved in.  I am still in early stages of my experimentation.

**Comment by nomatica** [comment]
@mikehardy  
> 
> Ah, that's clever on the append - you've left it basically as a "raw append" in the file, then the user can (and must...) do their own formatting, _including the newline_. So I think that's the key for @nomatica
> 
Definitely clever. 

> Love the references to other software. If someone wants to just copy-paste that into a wiki page here for "Systems Thunderlink Users Use" that would be more than fine by me. Great ideas.
Done... [https://github.com/mikehardy/thunderlink/wiki/Systems-Thunderlink-Users-Use](url)
Added a page to the wiki.  Copied and pasted....

**Comment by MarioKusek** [comment]
@nomatica 

> Do you think an escape sequence is needed just to get it into CVS format? I am not sure if my needs right now, justify needing to develop this feature. In the end, I am looking for a solution where I can keep track of emails as they relate to different tasks and projects I am involved in. I am still in early stages of my experimentation.

Well if you do not have character " in subject then it will work as is. If you have " then escaping is needed.  So for now if you want following columns: subject, sender and  time. You can put pattern:
`"<subject>","<sender>","<time>"\n`

since you are on windows and windows text files need to have line ending `\r\n` then for you this would be:
`"<subject>","<sender>","<time>"\r\n`

> The text file worked the best, however it was a single line, with spacing spacing between each link. 

This is because line engine in widows. If you add on end `\r\n` instead of `\n` it will work.

**Comment by nomatica** [comment]
@MarioKusek 
That worked like a charm. I know have it updating a cvs file which I can easily convert to a libre/excel spreadsheet.  I added the thunderlink to the pattern you offered.

**Comment by nomatica** [comment]
I saw mylifeorganized or mlo noted in the set-up instructions. I was curious if anyone had experience with that software?[](https://www.mylifeorganized.net)  Did the workflow with thunderlink consist of copying and pasting? Or using the append function?

**Comment by mikehardy** [comment]
@nomatica - the references to MLO were from the original author of the plugin, and I'm not sure how he used it, but it was certainly before append was implemented by Mario, so it must have been with links from clipboard, pasted somewhere (that was the original implementation)

**Comment by nbeaver** [comment]
I use desktop files, similar to this:

    [Desktop Entry]
    Name=Link to Debian 9.6 release announcement.
    Type=Link
    URL=thunderlink://messageid=a1528669-38a7-5a73-f044-9708e55fc24e@debian.org

This way I can navigate from the directory containing the desktop file directly to a relevant email or email chain. Unfortunately, Nautilus version 3.27.4 and later [does not support desktop files](https://gitlab.gnome.org/GNOME/nautilus/issues/448), so I'm not sure what I'll do once that becomes the default.

I also use Thunderlinks in [Zim wiki](https://zim-wiki.org/) a fair amount.

**Comment by novoid** [comment]
I'm using Org mode for almost anything on the computer. Really: https://karl-voit.at/orgmode/

Therefore, I'm linking emails from Thunderbird within my Org mode data: todos, projects, documentation, spreadsheets, diagrams, ....

Search for `thunderlink` within my config file for details on how to set this up: https://github.com/novoid/dot-emacs/blob/master/config.org

I'm very much looking forward for more format options so that I may have link descriptions that are more easily to read: #49
