### ISSUE TITLE
Feature request: open TLs by selecting in conversation

### ISSUE THREAD

**Issue by ericdanan** [mikehardy/thunderlink#43]
Hello,
Thank you for maintaining this add-on. Would it be possible to have an option so that when clicking on a thunderlink, the message is shown in a tab that displays the whole conversation? Currently I view the message in context and quite often I then click on the "conversation" button. The requested option would simply do that in one step without altering the main email tab.
I am of course happy to test if that can help.
Thanks for your attention.

**Comment by mikehardy** [comment]
It is certainly possible - I'm not familiar with those APIs so I can't say 100% that an API exists for that open style but I'd guess there was. Based on hours spent I'm about 230% busy on my day job at the moment so I don't have time to do it myself but I'll tag it as a generally okay idea and I'd be happy to merge a PR that did from anyone else. I'd be okay if the UI just added an extra combo box option for now
