### ISSUE TITLE
Recognize ThunderLinks and turn them into hyperlinks

### ISSUE THREAD

**Issue by JoeyAuf** [mikehardy/thunderlink#45]
Hello,

great addon! That's exactly what I was looking for. Only one thing I am missing. 
I am using OneNote and I can manually creat links to mails and it works. But if I just paste a link like "thunderlink://messageid=12345@mail.de" it does not turn into a hyperlink. Is that correkt or is there anything wrong with my setup?

I found an old addon for Firefox (thunderlinkspotter), which recognize ThunderLinks and turn them into hyperlinks. But it does not work anymore. Download on this side http://legacycollector.org/firefox-addons/314744/index.html

Is there any way to get this working?

I'm using Windows 7 64 bit, Onenote 2010, Thunderbird 60.7.0 32 bit, Firefox 67.0 64 bit.

Thanks for your work.
Joey

**Comment by mikehardy** [comment]
I'm not personally aware of a way to do this - I created and use the "clickable link" thunderlink shortcuts from the current preferences to do it

**Comment by JoeyAuf** [comment]
You mean the "clickable link" via html? <A HREF="thunderlink://messageid=1234@github.com">[1234/thunderlink] XXX </A>
Sadly you can not use html-code in OneNote. My workaround is to creat the hyperlink manually. Maybe I have to look for an other application.

Thanks for your fast help!

**Comment by mikehardy** [comment]
Hmm - yeah, that was the method I was aware of. I thought with protocol registration via the windows .reg files that thunderlink:// would be handled but if OneNote doesn't make arbitrary protocols clickable then that won't work, sorry. Seems like a general issue with OneNote that others have probably solved if there is any sort of OneNote forum to search and/or ask in?

**Comment by JoeyAuf** [comment]
Normal links, like www.xxx.com or http://xxx are automaticly turned into a hyperlink, if you meant this with protocol registration. But these are standard... Hmm maybe I'll look in a OneNote forum, good idea.

I just found out that if you send a thunderlink as mail it turns into a hyperlink and if you copy this it will stay a Hyperlink in OneNote. Is there a way to do this with the Thunderlink Options?

**Comment by mikehardy** [comment]
Re: the send as mail / copy hyperlink, that sounds non-standard, I'm not aware of any way to do this within thunderlink, sorry

**Comment by JoeyAuf** [comment]
allright, thanks for your help. If I find a solution, I'll post it.

**Comment by mikehardy** [comment]
Great - I will have my fingers crossed as I'd love to know myself. In the meantime I will close this as it is not really actionable but whatever you find, please do post it. Thanks
