### ISSUE TITLE
Feature Request: Open Specific Inbox Folder from -thunderlink Argument

### ISSUE THREAD

**Issue by Christian77777** [mikehardy/thunderlink#51]
Hello, I recently downloaded this plugin, and it seems to work great for opening individual messages.
However, I have spent the longest time trying to figure out if at all possible to start Thunderbird from the Command Line, to open a specific folder up in mail, either with this plugin or vanilla Thunderbird.
Personally, I have buttons on my Linux taskbar that show a inbox unread email counter for all my accounts. I would like to run a command when I click one, to open Thunderbird to the corresponding Inbox.
I was hoping to request this, since it doesn't stray far from the intention of this plugin. If possible to supply an argument of a Mailbox folder, to tell Thunderbird to open that Inbox. An example argument would be `imap://johnappleseed%40yahoo.com@imap.mail.yahoo.com/INBOX`
In my research I have found that this java script command in the error console does exactly what I need, when supplied with the above link as the server folder URL.
`top.OpenInboxForServer(MailUtils.getExistingFolr("<server folder url>").server)`
I have tested this to work with Thunderbird version 68.4.2
I understand the priority is to update to version 68, I only hope this will be considered past that.

**Comment by mikehardy** [comment]
Hi there! Sounds like you've already got the command working, I'm pretty busy in non-open-source work at the moment so I don't have time to hack on getting this work perfectly in TB68+ yet, but I don't see why that would block a PR that implemented this if you wanted to try one
