### ISSUE TITLE
Documentation change

### ISSUE THREAD

**Issue by artumi-richard** [mikehardy/thunderlink#52]
Hi. I just re-installed this to use with VimWiki after being away from it for a few years, I had trouble installing on Ubuntu 18.04 and eventually found success using the instructions here:

https://github.com/nbeaver/thunderlink-install-guide

I think the `gio mime x-scheme-handler/thunderlink thunderbird-thunderlink-handler.desktop` command needs to be in your docs. Also I found an old gist for others that might want to integrate VimWiki with Thunderlink, and you might want to reference that code somewhere

https://gist.github.com/artumi-richard/f5545b104e97a9ae444404d9b98f4b95

**Comment by mikehardy** [comment]
Hi there! Please feel free to propose any PRs that effect that change and/or add pages to the wiki to help people, that all sounds good

**Comment by nbeaver** [comment]
@artumi-richard Is this satisfied after https://github.com/mikehardy/thunderlink/pull/61 was merged? (https://github.com/mikehardy/thunderlink/commit/e800e6b7b26923b6c304e332cdd5838d9d748f79)

**Comment by artumi-richard** [comment]
I would say the most important part is. I don't know how much the VimWiki is just a part of my use-case. I suppose that's for others to judge. I wouldn't mind if you closed this.

**Comment by nbeaver** [comment]
@artumi-richard For the VimWiki part, I would encourage you to send a pull request to add it to the https://github.com/mikehardy/thunderlink/tree/master/integration folder. I haven't tried VimWiki but I'd like to someday and it would be nice to have that included in the repo. (P.S. I can't close this issue; I'm just the one that wrote the installer guide. I'm glad you found it helpful!)

**Comment by mikehardy** [comment]
PRs happily accepted :-), I'm also happy to add more maintainers, and in fact I should do. Look out in your inboxes. Cheers

**Comment by mikehardy** [comment]
@nbeaver  and @MarioKusek are both able to do commits now, with master branch protected from force pushes, requires a PR with one matching review. Should help in case I get hit by a bus! :-), no pressure though, this is a small volunteer project, just trying to spread things out a little bit in case someone feels motivated to make changes. I trust everyone to play nicely :-)
