### ISSUE TITLE
Feature Request: copy id of sent message to clipboard

### ISSUE THREAD

**Issue by rjoberon** [mikehardy/thunderlink#66]
It would be great if there would be an option to automatically copy the link for a sent message into the clipboard after the message has been sent. This could speed up task management and setting up reminders.

**Comment by mikehardy** [comment]
That sounds neat - I'd accept a PR that did that

This is definitely the repo of "the current implementation" but I must admit that I have fallen down on my getting things done habits so I haven't been making thorough use of thunderlink and it appears forward-porting to new thunderbirds is de-motivatingly hard, so the community will have to drive any innovation
